/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    copy: typeof import('./../src/components/ConnectWallet copy.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    NftTitle: typeof import('./../src/components/NftTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserWallet: typeof import('./../src/components/UserWallet.vue')['default']
  }
}

// For TSX support
declare global {
  const AAvatar: (typeof import('@arco-design/web-vue'))['Avatar']
  const AButton: (typeof import('@arco-design/web-vue'))['Button']
  const ACol: (typeof import('@arco-design/web-vue'))['Col']
  const ADoption: (typeof import('@arco-design/web-vue'))['Doption']
  const ADropdown: (typeof import('@arco-design/web-vue'))['Dropdown']
  const AForm: (typeof import('@arco-design/web-vue'))['Form']
  const AFormItem: (typeof import('@arco-design/web-vue'))['FormItem']
  const AInput: (typeof import('@arco-design/web-vue'))['Input']
  const AInputNumber: (typeof import('@arco-design/web-vue'))['InputNumber']
  const AModal: (typeof import('@arco-design/web-vue'))['Modal']
  const AProgress: (typeof import('@arco-design/web-vue'))['Progress']
  const ARow: (typeof import('@arco-design/web-vue'))['Row']
  const ASpace: (typeof import('@arco-design/web-vue'))['Space']
  const ASpin: (typeof import('@arco-design/web-vue'))['Spin']
  const ATag: (typeof import('@arco-design/web-vue'))['Tag']
  const ATextarea: (typeof import('@arco-design/web-vue'))['Textarea']
  const ConnectWallet: (typeof import('./../src/components/ConnectWallet.vue'))['default']
  const copy: (typeof import('./../src/components/ConnectWallet copy.vue'))['default']
  const Header: (typeof import('./../src/components/Header.vue'))['default']
  const NftTitle: (typeof import('./../src/components/NftTitle.vue'))['default']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const UserWallet: (typeof import('./../src/components/UserWallet.vue'))['default']
}
