/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    Header: typeof import('./../src/components/Header.vue')['default']
    NftTitle: typeof import('./../src/components/NftTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AButton: typeof import('@arco-design/web-vue')['Button']
  const ACol: typeof import('@arco-design/web-vue')['Col']
  const AForm: typeof import('@arco-design/web-vue')['Form']
  const AFormItem: typeof import('@arco-design/web-vue')['FormItem']
  const AInput: typeof import('@arco-design/web-vue')['Input']
  const AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
  const AProgress: typeof import('@arco-design/web-vue')['Progress']
  const ARow: typeof import('@arco-design/web-vue')['Row']
  const ASpin: typeof import('@arco-design/web-vue')['Spin']
  const ATextarea: typeof import('@arco-design/web-vue')['Textarea']
  const Header: typeof import('./../src/components/Header.vue')['default']
  const NftTitle: typeof import('./../src/components/NftTitle.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}